# Site settings
title: "Christian J. Tai Udovicic | Planetary Scientist"
description: "Christian is a postdoc exploring the Moon at Northern Arizona University."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Christian J. Tai Udovicic"
resume_title:                   "Postdoctoral Scholar"
resume_contact_email:           "cjtu@nau.edu"
resume_contact_telephone:       "928-266-4451"
resume_contact_address:         ""
resume_header_contact_info:     ""
resume_header_intro: >-
    <p>I use orbital data and code to understand how the Moon changes over time. 
    I am passionate about open source science and social justice. While you're here, you can
    download pdfs of my <a href="#publications" itemprop="url">papers</a>, 
    check out my free coding textbook <a href="https://cjtu.github.io/spirl" itemprop="url">SPIRL</a>, 
    or see my current <a href="#projects" itemprop="url">GitHub projects</a>.</p>

# Comment out unused sections
# resume_section_associations:    true
resume_section_education:       true
resume_section_experience:      true
# resume_section_interests:       true
# resume_section_links:           true
resume_section_outreach:        true
resume_section_presentations:   true
resume_section_projects:       true
resume_section_publications:    true
resume_section_recognition:     true
# resume_section_skills:         true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/cjtu"
  resume_twitter_url:           "https://twitter.com/TaiUdovicic"
  # resume_dribbble_url:
  # resume_facebook_url:
  resume_linkedin_url:          "https://www.linkedin.com/in/christian-tai-udovicic"
  # resume_instagram_url:
  resume_website_url:           "https://cjtu.github.io/"
resume_print_social_links:      true

# Option to add a Goggle analytics tracking code
# Navigate to https://analytics.google.com, add a new property for your site and copy the tracking id here.
google_analytics:
  mytrackingcode: UA-111642150-2

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
