# Site settings
title: "Christian Tai Udovicic"
description: "Christian Tai Udovicic is a graduate researcher at Northern Arizona University."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Christian J. Tai Udovicic"
resume_title:                   "Graduate Student"
resume_contact_email:           "cjt347@nau.edu"
resume_contact_telephone:       "928-266-4451"
resume_contact_address:         ""
resume_header_contact_info:     ""
resume_header_intro:            "<p>I am a planetary scienist in the Astronomy and Planetary Science PhD program at Northern Arizona University. My current research interests involve lunar surface processes, including space weathering, cratering, and the production and distribution of volatiles on the Moon. All inquiries can be addressed to <a style='color:#999;' href='mailto:cj.taiudovicic@gmail.com'>cj.taiudovicic@gmail.com</a>.</p>"

# Comment out unused sections
# resume_section_associations:    true
resume_section_education:       true
# resume_section_experience:      true
# resume_section_interests:       true
# resume_section_links:           true
resume_section_outreach:        true
resume_section_presentations:   true
# resume_section_projects:       true
resume_section_publications:    true
resume_section_recognition:     true
# resume_section_skills:         true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/cjtu"
  resume_twitter_url:           "http://twitter.com/TaiUdovicic"
  # resume_dribbble_url:
  # resume_facebook_url:
  resume_linkedin_url:          "https://www.linkedin.com/in/christian-tai-udovicic"
  # resume_instagram_url:
  resume_website_url:           "http://cjtu.github.io/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
